### PR TITLE
Change css styling to render dropdown menu horizontal instead of vertical

### LINKED ISSUE #7: Dropdown menu for About should show links arranged vertically
The **About** menu added in #4 looks a little different to the one for the main website:

**This theme**

Screenshot 2019-04-24 at 14 01 48

**Main astropy.org website**

Screenshot 2019-04-24 at 14 01 55

@kakirastern - is there any way to make the one here resemble the website one more?

### PR DESCRIPTION
**Pull request by kakirastern**
Fixes #7. 

Made changes to the `bootstrap-astropy.css` file so that the dropdown menu item is vertically arranged instead of being horizontal.

### CODE REVIEW

**Comment by kakirastern** [comment]
This is what I get when building the astropy docs locally:

Screenshot 2019-04-24 22 03 45

**Comment by astrofrog** [comment]
@kakirastern - perfect, thanks! Can you rebase this on the latest upstream master? This should get rid of the merge commit.

**Comment by kakirastern** [comment]
Sorry, been having issues with rebasing this PR before so took several attempts to make it work... Kept pulling commits to my local repo that shouldn't be there by `git pull`... Now it should work.

**Comment by bsipocz** [comment]
@kakirastern - the trick is that `git pull` never needs to be used (at least never in the context of a rebase).

**Comment by kakirastern** [comment]
Okay, I see

**Pull request merged**
